### PR TITLE
Handle ipv6 and multiple hostnames

### LINKED ISSUE #4: Multiple host
Will it be considered to support multiple host names (e.g. `mongodb://host1:27017,host2:27017`)?

### PR DESCRIPTION
**Pull request by kevinresol**
Closes #4 & #5

### CODE REVIEW

**Comment by kevinresol** [comment]
I think the change is quite minimal, there shouldn't be much impact on performance. But IMO this make the library more useful.

Anyway feel free to close if it does not match the purpose of the lib. I will copy the code somewhere so I can use in my projects. 😄

**Comment by back2dos** [comment]
Well, closing #5 is definitely useful. I have [some reservation](https://github.com/haxetink/tink_url/issues/4#issuecomment-217907623) about the other part, but let me think about it.

**Comment by kevinresol** [comment]
I am packing several enhancements in this PR, let me know if you need me to separate them.

**Comment by back2dos** [comment]
You know what, let me just merge this and then deal with my perfectionism when I have the time :)

**Comment by kevinresol** [comment]
Thanks! And I do love perfection! (just I am not perfect enough to be a perfectionist lol)

**Comment by back2dos** [comment]
So do I. But perfectionism is to perfection what oversimplification is to simplicity ;)

**Pull request merged**
